---
- name: install git
  yum: 
    name: git
    state: installed

- name: install gcc
  yum: 
    name: gcc
    state: installed

- name: install jq
  yum: 
    name: jq
    state: installed
    enablerepo: epel

- name: install expect
  yum: 
    name: expect
    state: installed

- name: install ImageMagick
  yum: 
    name: ImageMagick
    state: installed

- name: install bash-completion
  yum: 
    name: bash-completion
    state: installed
    enablerepo: epel

- name: install nkf
  yum: 
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/n/nkf-2.1.3-5.el7.x86_64.rpm
    state: installed
